// InviteLink — inviter side of the new link-based invite flow.
// Creates an invite link server-side, shows it for sharing, then auto-processes
// the joiner's KP via WASM (addMember) and delivers the Welcome when they click join.
import React, { useState, useEffect, useRef } from 'react';
import { MlsClient, MlsGroup, KeyPackage } from '../../mls/index';
import { useToastContext } from '../../contexts/ToastContext';
import { saveAndSyncWasmState } from '../../utils/wasmStateSync';
import { Check, Copy, Link } from 'lucide-react';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const ANON_KEY = (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ?? '';

function authHeaders() {
  return {
    'Content-Type': 'application/json',
    'apikey': ANON_KEY,
    'Authorization': `Bearer ${localStorage.getItem('authToken') ?? ANON_KEY}`,
  };
}

interface InviteLinkProps {
  groupId: string;
  userId: string;
  deviceId: string;
  mlsGroup: MlsGroup;
  mlsClient: MlsClient;
}

type Status = 'creating' | 'waiting' | 'processing' | 'done' | 'error';

export const InviteLink: React.FC<InviteLinkProps> = ({
  groupId,
  userId,
  deviceId,
  mlsGroup,
  mlsClient,
}) => {
  const [status, setStatus] = useState<Status>('creating');
  const [inviteId, setInviteId] = useState<string | null>(null);
  const [inviteUrl, setInviteUrl] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const pollingRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const toast = useToastContext();

  // Create invite on mount
  useEffect(() => {
    if (!SUPABASE_URL) {
      setErrorMsg('Configuration error');
      setStatus('error');
      return;
    }

    fetch(`${SUPABASE_URL}/functions/v1/invite_create`, {
      method: 'POST',
      headers: authHeaders(),
      body: JSON.stringify({ group_id: groupId, user_id: userId, device_id: deviceId }),
    })
      .then(r => r.json())
      .then((data: { invite_id?: string; error?: string }) => {
        if (data.error || !data.invite_id) {
          setErrorMsg(data.error ?? 'Failed to create invite');
          setStatus('error');
          return;
        }
        const id = data.invite_id;
        const url = `${window.location.origin}?join=${id}`;
        setInviteId(id);
        setInviteUrl(url);
        setStatus('waiting');
      })
      .catch(() => {
        setErrorMsg('Failed to create invite');
        setStatus('error');
      });
  }, [groupId, userId, deviceId]);

  // Poll for pending KP while waiting
  useEffect(() => {
    if (status !== 'waiting' || !inviteId || !SUPABASE_URL) return;

    pollingRef.current = setInterval(async () => {
      try {
        const res = await fetch(`${SUPABASE_URL}/functions/v1/invite_pending`, {
          method: 'POST',
          headers: authHeaders(),
          body: JSON.stringify({ user_id: userId, device_id: deviceId }),
        });
        const data = await res.json() as {
          invites?: Array<{ invite_id: string; group_id: string; kp_hex: string }>;
        };

        const match = (data.invites ?? []).find(inv => inv.invite_id === inviteId);
        if (!match) return;

        if (pollingRef.current) clearInterval(pollingRef.current);
        setStatus('processing');

        // WASM: addMember with joiner's key package
        const kp: KeyPackage = {
          data: match.kp_hex,
          signature: '',
          hpkePublicKey: '',
          credential: '',
          extensions: {},
        };
        const result = await mlsClient.addMember(mlsGroup, kp);
        if (!result.welcome) throw new Error('Welcome not generated by WASM');

        // Deliver welcome to server
        const completeRes = await fetch(`${SUPABASE_URL}/functions/v1/invite_complete`, {
          method: 'POST',
          headers: authHeaders(),
          body: JSON.stringify({
            invite_id: inviteId,
            user_id: userId,
            device_id: deviceId,
            welcome_hex: result.welcome,
          }),
        });
        const completeData = await completeRes.json() as { ok?: boolean; error?: string };
        if (!completeData.ok) throw new Error(completeData.error ?? 'Failed to complete invite');

        // Persist updated WASM state (epoch advanced after addMember)
        const stateJson = await mlsClient.exportState();
        await saveAndSyncWasmState(userId, deviceId, stateJson);

        setStatus('done');
        toast.success('Member added successfully!');
      } catch (e) {
        console.error('[InviteLink] processing error:', e);
        setErrorMsg(e instanceof Error ? e.message : 'Failed to process invite');
        setStatus('error');
        if (pollingRef.current) clearInterval(pollingRef.current);
      }
    }, 5000);

    return () => {
      if (pollingRef.current) clearInterval(pollingRef.current);
    };
  }, [status, inviteId, userId, deviceId, mlsGroup, mlsClient]);

  const handleCopy = async () => {
    if (!inviteUrl) return;
    await navigator.clipboard.writeText(inviteUrl);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-4">
      <p className="font-mono text-[10px] text-white/30 uppercase tracking-widest">Invite member</p>

      {/* Creating */}
      {status === 'creating' && (
        <div className="flex items-center gap-2">
          <span className="inline-block w-1.5 h-1.5 rounded-full bg-white/20 animate-pulse" />
          <span className="font-mono text-[11px] text-white/25">Generating link…</span>
        </div>
      )}

      {/* Error */}
      {status === 'error' && (
        <p className="text-[12px] text-red-400/60">{errorMsg ?? 'Something went wrong.'}</p>
      )}

      {/* Done */}
      {status === 'done' && (
        <div className="flex items-center gap-2 text-white/50">
          <Check size={13} />
          <span className="text-[13px]">Member joined successfully.</span>
        </div>
      )}

      {/* Waiting / Processing — show link */}
      {(status === 'waiting' || status === 'processing') && inviteUrl && (
        <div className="space-y-3">
          <p className="text-[12px] text-white/45">
            Send this link to the person you want to invite:
          </p>

          {/* Link row */}
          <div className="flex items-center gap-0 border border-white/10">
            <div className="flex items-center gap-2 flex-1 px-3 py-2.5 min-w-0">
              <Link size={11} className="text-white/20 shrink-0" />
              <span className="font-mono text-[11px] text-white/45 truncate">{inviteUrl}</span>
            </div>
            <button
              onClick={handleCopy}
              className="px-3 py-2.5 border-l border-white/10 text-white/35 hover:text-white hover:bg-white/5 active:bg-white/10 transition-colors shrink-0"
              title="Copy link"
            >
              {copied
                ? <Check size={13} className="text-white/60" />
                : <Copy size={13} />
              }
            </button>
          </div>

          {/* Status row */}
          <div className="flex items-center gap-2">
            {status === 'waiting' ? (
              <>
                <span className="inline-block w-1.5 h-1.5 rounded-full bg-white/25 animate-pulse" />
                <span className="font-mono text-[10px] text-white/25 uppercase tracking-widest">
                  Waiting for them to join…
                </span>
              </>
            ) : (
              <>
                <span className="inline-block w-1.5 h-1.5 rounded-full bg-white/40 animate-pulse" />
                <span className="font-mono text-[10px] text-white/35 uppercase tracking-widest">
                  Processing…
                </span>
              </>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default InviteLink;
